ref: /home/robert-kofler/analysis/2026-tutorial/02-snakemake/refg/dmel-tes-scg.fasta
readdir: /home/robert-kofler/analysis/2026-tutorial/02-snakemake/rawdata
outdir: /home/robert-kofler/analysis/2026-tutorial/02-snakemake/bb-map
